'use client';

import type { ReactNode } from 'react';
import type { DocumentParty, DocumentWarehouse } from '@/server/documents';

/**
 * The paper-like chrome shared by every printable document: a screen-only toolbar
 * with the print action, the TechnicoFlor letterhead, the document meta, the party block,
 * and a slot for the document body (its line table). Fixed light styling so it reads
 * as a document in either app theme and prints cleanly.
 */
export function DocSheet({
  title,
  number,
  date,
  dueDate,
  status,
  orderCode,
  party,
  partyLabel = 'Bill to',
  warehouse,
  pdfHref,
  children,
}: {
  title: string;
  number: string;
  date: string;
  dueDate?: string;
  status?: string;
  orderCode?: string;
  party: DocumentParty;
  partyLabel?: string;
  warehouse?: DocumentWarehouse | null;
  pdfHref?: string;
  children: ReactNode;
}) {
  return (
    <div className="doc-page">
      <div className="doc-toolbar no-print">
        <button className="btn btn-sm" onClick={() => window.print()}>
          Print
        </button>
        {pdfHref && (
          <a className="btn btn-sm btn-ghost" href={pdfHref} target="_blank" rel="noopener noreferrer">
            Download PDF
          </a>
        )}
      </div>

      <div className="doc-sheet">
        <header className="flex items-start justify-between gap-6">
          <div>
            <div className="flex items-center gap-2">
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img src="/brand/mark.png" alt="" width={26} height={30} className="h-[26px] w-auto" />
              <span className="text-[1.3rem] font-semibold tracking-[0.01em]">TechnicoFlor</span>
            </div>
            <div className="text-[0.78rem] text-[#6b7280]">Perfume Manufacturing &amp; Distribution</div>
          </div>
          <div className="text-right">
            <div className="text-[1.1rem] font-semibold uppercase tracking-[0.08em]">{title}</div>
            <div className="mt-1 text-[0.85rem]">
              <span className="text-[#6b7280]">No. </span>
              <span className="font-medium">{number}</span>
            </div>
            <div className="text-[0.85rem]">
              <span className="text-[#6b7280]">Date </span>
              {date}
            </div>
            {dueDate && (
              <div className="text-[0.85rem]">
                <span className="text-[#6b7280]">Due </span>
                {dueDate}
              </div>
            )}
            {orderCode && (
              <div className="text-[0.85rem]">
                <span className="text-[#6b7280]">Order </span>
                {orderCode}
              </div>
            )}
            {status && (
              <div className="mt-1 text-[0.72rem] uppercase tracking-[0.06em] text-[#6b7280]">
                {status.replace(/_/g, ' ')}
              </div>
            )}
          </div>
        </header>

        <div className="mt-8 flex flex-wrap justify-between gap-6 text-[0.85rem]">
          <div>
            <div className="mb-1 text-[0.7rem] font-semibold uppercase tracking-[0.06em] text-[#6b7280]">
              {partyLabel}
            </div>
            <div className="font-medium">{party.name}</div>
            <div className="text-[#4b5563]">{party.code}</div>
            {party.address && <div className="whitespace-pre-line text-[#4b5563]">{party.address}</div>}
            {party.email && <div className="text-[#4b5563]">{party.email}</div>}
            {party.phone && <div className="text-[#4b5563]">{party.phone}</div>}
          </div>
          {warehouse && (
            <div className="text-right">
              <div className="mb-1 text-[0.7rem] font-semibold uppercase tracking-[0.06em] text-[#6b7280]">
                Dispatched from
              </div>
              <div className="font-medium">{warehouse.name}</div>
              <div className="text-[#4b5563]">{warehouse.code}</div>
            </div>
          )}
        </div>

        <div className="mt-8">{children}</div>

        <footer className="mt-10 border-t border-[#eceef1] pt-4 text-[0.72rem] text-[#9ca3af]">
          Generated by TechnicoFlor — reflects recorded order data at time of printing.
        </footer>
      </div>
    </div>
  );
}

/** Shared loading / error / empty state for a document page, styled as a sheet. */
export function DocState({ children }: { children: ReactNode }) {
  return (
    <div className="doc-page">
      <div className="doc-sheet text-[0.9rem] text-[#6b7280]">{children}</div>
    </div>
  );
}
