// Generated by scripts/gen-types.mjs from the public schema. Do not edit by hand.
// Regenerate after a migration:  yarn gen:types
// (For your live project you can equivalently run:
//   supabase gen types typescript --linked --schema public > src/types/database.ts)

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      app_users: {
        Row: {
          user_id: string
          role: Database["public"]["Enums"]["app_role"]
          created_at: string
        };
        Insert: {
          user_id: string
          role?: Database["public"]["Enums"]["app_role"]
          created_at?: string
        };
        Update: {
          user_id?: string
          role?: Database["public"]["Enums"]["app_role"]
          created_at?: string
        };
        Relationships: [];
      };
      customers: {
        Row: {
          id: string
          code: string
          name: string
          email: string | null
          phone: string | null
          address: string | null
          created_at: string
        };
        Insert: {
          id?: string
          code: string
          name: string
          email?: string | null
          phone?: string | null
          address?: string | null
          created_at?: string
        };
        Update: {
          id?: string
          code?: string
          name?: string
          email?: string | null
          phone?: string | null
          address?: string | null
          created_at?: string
        };
        Relationships: [];
      };
      formula_components: {
        Row: {
          id: string
          formula_version_id: string
          raw_material_id: string
          quantity: number
          unit: Database["public"]["Enums"]["unit_code"]
          sequence: number
        };
        Insert: {
          id?: string
          formula_version_id: string
          raw_material_id: string
          quantity: number
          unit: Database["public"]["Enums"]["unit_code"]
          sequence?: number
        };
        Update: {
          id?: string
          formula_version_id?: string
          raw_material_id?: string
          quantity?: number
          unit?: Database["public"]["Enums"]["unit_code"]
          sequence?: number
        };
        Relationships: [
          {
            foreignKeyName: "formula_components_formula_version_id_fkey";
            columns: ["formula_version_id"];
            isOneToOne: false;
            referencedRelation: "formula_versions";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "formula_components_raw_material_id_fkey";
            columns: ["raw_material_id"];
            isOneToOne: false;
            referencedRelation: "raw_materials";
            referencedColumns: ["id"];
          }
        ];
      };
      formula_versions: {
        Row: {
          id: string
          formula_id: string
          version_no: number
          basis: Database["public"]["Enums"]["formula_basis"]
          is_locked: boolean
          created_at: string
        };
        Insert: {
          id?: string
          formula_id: string
          version_no: number
          basis: Database["public"]["Enums"]["formula_basis"]
          is_locked?: boolean
          created_at?: string
        };
        Update: {
          id?: string
          formula_id?: string
          version_no?: number
          basis?: Database["public"]["Enums"]["formula_basis"]
          is_locked?: boolean
          created_at?: string
        };
        Relationships: [
          {
            foreignKeyName: "formula_versions_formula_id_fkey";
            columns: ["formula_id"];
            isOneToOne: false;
            referencedRelation: "formulas";
            referencedColumns: ["id"];
          }
        ];
      };
      formulas: {
        Row: {
          id: string
          code: string
          name: string
          product_id: string | null
          created_at: string
        };
        Insert: {
          id?: string
          code: string
          name: string
          product_id?: string | null
          created_at?: string
        };
        Update: {
          id?: string
          code?: string
          name?: string
          product_id?: string | null
          created_at?: string
        };
        Relationships: [
          {
            foreignKeyName: "formulas_product_id_fkey";
            columns: ["product_id"];
            isOneToOne: false;
            referencedRelation: "products";
            referencedColumns: ["id"];
          }
        ];
      };
      inventory_lots: {
        Row: {
          id: string
          lot_code: string
          item_type: string
          raw_material_id: string | null
          product_id: string | null
          warehouse_id: string
          quantity_on_hand: number
          unit: Database["public"]["Enums"]["unit_code"]
          status: Database["public"]["Enums"]["lot_status"]
          expiry_date: string | null
          received_at: string
          unit_cost: number | null
        };
        Insert: {
          id?: string
          lot_code: string
          item_type: string
          raw_material_id?: string | null
          product_id?: string | null
          warehouse_id: string
          quantity_on_hand?: number
          unit: Database["public"]["Enums"]["unit_code"]
          status?: Database["public"]["Enums"]["lot_status"]
          expiry_date?: string | null
          received_at?: string
          unit_cost?: number | null
        };
        Update: {
          id?: string
          lot_code?: string
          item_type?: string
          raw_material_id?: string | null
          product_id?: string | null
          warehouse_id?: string
          quantity_on_hand?: number
          unit?: Database["public"]["Enums"]["unit_code"]
          status?: Database["public"]["Enums"]["lot_status"]
          expiry_date?: string | null
          received_at?: string
          unit_cost?: number | null
        };
        Relationships: [
          {
            foreignKeyName: "inventory_lots_product_id_fkey";
            columns: ["product_id"];
            isOneToOne: false;
            referencedRelation: "products";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "inventory_lots_raw_material_id_fkey";
            columns: ["raw_material_id"];
            isOneToOne: false;
            referencedRelation: "raw_materials";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "inventory_lots_warehouse_id_fkey";
            columns: ["warehouse_id"];
            isOneToOne: false;
            referencedRelation: "warehouses";
            referencedColumns: ["id"];
          }
        ];
      };
      lot_genealogy: {
        Row: {
          id: string
          parent_lot_id: string
          child_lot_id: string
          production_order_id: string
          quantity: number
          unit: Database["public"]["Enums"]["unit_code"]
          created_at: string
        };
        Insert: {
          id?: string
          parent_lot_id: string
          child_lot_id: string
          production_order_id: string
          quantity: number
          unit: Database["public"]["Enums"]["unit_code"]
          created_at?: string
        };
        Update: {
          id?: string
          parent_lot_id?: string
          child_lot_id?: string
          production_order_id?: string
          quantity?: number
          unit?: Database["public"]["Enums"]["unit_code"]
          created_at?: string
        };
        Relationships: [
          {
            foreignKeyName: "lot_genealogy_child_lot_id_fkey";
            columns: ["child_lot_id"];
            isOneToOne: false;
            referencedRelation: "inventory_lots";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "lot_genealogy_parent_lot_id_fkey";
            columns: ["parent_lot_id"];
            isOneToOne: false;
            referencedRelation: "inventory_lots";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "lot_genealogy_production_order_id_fkey";
            columns: ["production_order_id"];
            isOneToOne: false;
            referencedRelation: "production_orders";
            referencedColumns: ["id"];
          }
        ];
      };
      production_consumptions: {
        Row: {
          id: string
          production_order_id: string
          lot_id: string
          raw_material_id: string
          quantity: number
          unit: Database["public"]["Enums"]["unit_code"]
          cost: number | null
        };
        Insert: {
          id?: string
          production_order_id: string
          lot_id: string
          raw_material_id: string
          quantity: number
          unit: Database["public"]["Enums"]["unit_code"]
          cost?: number | null
        };
        Update: {
          id?: string
          production_order_id?: string
          lot_id?: string
          raw_material_id?: string
          quantity?: number
          unit?: Database["public"]["Enums"]["unit_code"]
          cost?: number | null
        };
        Relationships: [
          {
            foreignKeyName: "production_consumptions_lot_id_fkey";
            columns: ["lot_id"];
            isOneToOne: false;
            referencedRelation: "inventory_lots";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "production_consumptions_production_order_id_fkey";
            columns: ["production_order_id"];
            isOneToOne: false;
            referencedRelation: "production_orders";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "production_consumptions_raw_material_id_fkey";
            columns: ["raw_material_id"];
            isOneToOne: false;
            referencedRelation: "raw_materials";
            referencedColumns: ["id"];
          }
        ];
      };
      production_order_components: {
        Row: {
          id: string
          production_order_id: string
          raw_material_id: string
          planned_quantity: number
          unit: Database["public"]["Enums"]["unit_code"]
        };
        Insert: {
          id?: string
          production_order_id: string
          raw_material_id: string
          planned_quantity: number
          unit: Database["public"]["Enums"]["unit_code"]
        };
        Update: {
          id?: string
          production_order_id?: string
          raw_material_id?: string
          planned_quantity?: number
          unit?: Database["public"]["Enums"]["unit_code"]
        };
        Relationships: [
          {
            foreignKeyName: "production_order_components_production_order_id_fkey";
            columns: ["production_order_id"];
            isOneToOne: false;
            referencedRelation: "production_orders";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "production_order_components_raw_material_id_fkey";
            columns: ["raw_material_id"];
            isOneToOne: false;
            referencedRelation: "raw_materials";
            referencedColumns: ["id"];
          }
        ];
      };
      production_orders: {
        Row: {
          id: string
          code: string
          product_id: string
          formula_version_id: string
          warehouse_id: string
          planned_quantity: number
          unit: Database["public"]["Enums"]["unit_code"]
          status: Database["public"]["Enums"]["production_status"]
          output_lot_id: string | null
          created_at: string
          completed_at: string | null
        };
        Insert: {
          id?: string
          code: string
          product_id: string
          formula_version_id: string
          warehouse_id: string
          planned_quantity: number
          unit: Database["public"]["Enums"]["unit_code"]
          status?: Database["public"]["Enums"]["production_status"]
          output_lot_id?: string | null
          created_at?: string
          completed_at?: string | null
        };
        Update: {
          id?: string
          code?: string
          product_id?: string
          formula_version_id?: string
          warehouse_id?: string
          planned_quantity?: number
          unit?: Database["public"]["Enums"]["unit_code"]
          status?: Database["public"]["Enums"]["production_status"]
          output_lot_id?: string | null
          created_at?: string
          completed_at?: string | null
        };
        Relationships: [
          {
            foreignKeyName: "production_orders_formula_version_id_fkey";
            columns: ["formula_version_id"];
            isOneToOne: false;
            referencedRelation: "formula_versions";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "production_orders_output_lot_id_fkey";
            columns: ["output_lot_id"];
            isOneToOne: false;
            referencedRelation: "inventory_lots";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "production_orders_product_id_fkey";
            columns: ["product_id"];
            isOneToOne: false;
            referencedRelation: "products";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "production_orders_warehouse_id_fkey";
            columns: ["warehouse_id"];
            isOneToOne: false;
            referencedRelation: "warehouses";
            referencedColumns: ["id"];
          }
        ];
      };
      products: {
        Row: {
          id: string
          sku: string
          name: string
          base_unit: Database["public"]["Enums"]["unit_code"]
          created_at: string
        };
        Insert: {
          id?: string
          sku: string
          name: string
          base_unit: Database["public"]["Enums"]["unit_code"]
          created_at?: string
        };
        Update: {
          id?: string
          sku?: string
          name?: string
          base_unit?: Database["public"]["Enums"]["unit_code"]
          created_at?: string
        };
        Relationships: [];
      };
      qc_checks: {
        Row: {
          id: string
          lot_id: string
          production_order_id: string | null
          status: Database["public"]["Enums"]["qc_status"]
          specific_gravity: number | null
          alcohol_pct: number | null
          notes: string | null
          checked_by: string | null
          checked_at: string | null
        };
        Insert: {
          id?: string
          lot_id: string
          production_order_id?: string | null
          status?: Database["public"]["Enums"]["qc_status"]
          specific_gravity?: number | null
          alcohol_pct?: number | null
          notes?: string | null
          checked_by?: string | null
          checked_at?: string | null
        };
        Update: {
          id?: string
          lot_id?: string
          production_order_id?: string | null
          status?: Database["public"]["Enums"]["qc_status"]
          specific_gravity?: number | null
          alcohol_pct?: number | null
          notes?: string | null
          checked_by?: string | null
          checked_at?: string | null
        };
        Relationships: [
          {
            foreignKeyName: "qc_checks_lot_id_fkey";
            columns: ["lot_id"];
            isOneToOne: false;
            referencedRelation: "inventory_lots";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "qc_checks_production_order_id_fkey";
            columns: ["production_order_id"];
            isOneToOne: false;
            referencedRelation: "production_orders";
            referencedColumns: ["id"];
          }
        ];
      };
      raw_materials: {
        Row: {
          id: string
          sku: string
          name: string
          category: Database["public"]["Enums"]["material_category"]
          base_unit: Database["public"]["Enums"]["unit_code"]
          density_g_per_ml: number | null
          standard_cost: number
          is_flammable: boolean
          created_at: string
        };
        Insert: {
          id?: string
          sku: string
          name: string
          category: Database["public"]["Enums"]["material_category"]
          base_unit: Database["public"]["Enums"]["unit_code"]
          density_g_per_ml?: number | null
          standard_cost?: number
          is_flammable?: boolean
          created_at?: string
        };
        Update: {
          id?: string
          sku?: string
          name?: string
          category?: Database["public"]["Enums"]["material_category"]
          base_unit?: Database["public"]["Enums"]["unit_code"]
          density_g_per_ml?: number | null
          standard_cost?: number
          is_flammable?: boolean
          created_at?: string
        };
        Relationships: [];
      };
      sales_order_lines: {
        Row: {
          id: string
          sales_order_id: string
          product_id: string
          quantity: number
          unit: Database["public"]["Enums"]["unit_code"]
          unit_price: number
          shipped_quantity: number
          cogs: number | null
        };
        Insert: {
          id?: string
          sales_order_id: string
          product_id: string
          quantity: number
          unit: Database["public"]["Enums"]["unit_code"]
          unit_price?: number
          shipped_quantity?: number
          cogs?: number | null
        };
        Update: {
          id?: string
          sales_order_id?: string
          product_id?: string
          quantity?: number
          unit?: Database["public"]["Enums"]["unit_code"]
          unit_price?: number
          shipped_quantity?: number
          cogs?: number | null
        };
        Relationships: [
          {
            foreignKeyName: "sales_order_lines_product_id_fkey";
            columns: ["product_id"];
            isOneToOne: false;
            referencedRelation: "products";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "sales_order_lines_sales_order_id_fkey";
            columns: ["sales_order_id"];
            isOneToOne: false;
            referencedRelation: "sales_orders";
            referencedColumns: ["id"];
          }
        ];
      };
      sales_orders: {
        Row: {
          id: string
          code: string
          customer_id: string
          warehouse_id: string
          status: Database["public"]["Enums"]["sales_order_status"]
          order_date: string
          created_at: string
        };
        Insert: {
          id?: string
          code: string
          customer_id: string
          warehouse_id: string
          status?: Database["public"]["Enums"]["sales_order_status"]
          order_date?: string
          created_at?: string
        };
        Update: {
          id?: string
          code?: string
          customer_id?: string
          warehouse_id?: string
          status?: Database["public"]["Enums"]["sales_order_status"]
          order_date?: string
          created_at?: string
        };
        Relationships: [
          {
            foreignKeyName: "sales_orders_customer_id_fkey";
            columns: ["customer_id"];
            isOneToOne: false;
            referencedRelation: "customers";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "sales_orders_warehouse_id_fkey";
            columns: ["warehouse_id"];
            isOneToOne: false;
            referencedRelation: "warehouses";
            referencedColumns: ["id"];
          }
        ];
      };
      stock_movements: {
        Row: {
          id: string
          lot_id: string
          movement_type: Database["public"]["Enums"]["movement_type"]
          quantity: number
          unit: Database["public"]["Enums"]["unit_code"]
          reference_type: string | null
          reference_id: string | null
          created_by: string | null
          created_at: string
        };
        Insert: {
          id?: string
          lot_id: string
          movement_type: Database["public"]["Enums"]["movement_type"]
          quantity: number
          unit: Database["public"]["Enums"]["unit_code"]
          reference_type?: string | null
          reference_id?: string | null
          created_by?: string | null
          created_at?: string
        };
        Update: {
          id?: string
          lot_id?: string
          movement_type?: Database["public"]["Enums"]["movement_type"]
          quantity?: number
          unit?: Database["public"]["Enums"]["unit_code"]
          reference_type?: string | null
          reference_id?: string | null
          created_by?: string | null
          created_at?: string
        };
        Relationships: [
          {
            foreignKeyName: "stock_movements_lot_id_fkey";
            columns: ["lot_id"];
            isOneToOne: false;
            referencedRelation: "inventory_lots";
            referencedColumns: ["id"];
          }
        ];
      };
      warehouses: {
        Row: {
          id: string
          code: string
          name: string
          created_at: string
        };
        Insert: {
          id?: string
          code: string
          name: string
          created_at?: string
        };
        Update: {
          id?: string
          code?: string
          name?: string
          created_at?: string
        };
        Relationships: [];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      _ship_order_line: {
        Args: {
          p_line_id: string
          p_warehouse_id: string
          p_target: number
          p_strict: boolean
          p_user: string
        };
        Returns: number;
      };
      admin_check_user_deletable: {
        Args: {
          p_user_id: string
        };
        Returns: string;
      };
      admin_create_formula_version: {
        Args: {
          p_formula_id: string
          p_basis: Database["public"]["Enums"]["formula_basis"]
          p_clone_from?: string
        };
        Returns: string;
      };
      admin_delete_formula_version: {
        Args: {
          p_vid: string
        };
        Returns: undefined;
      };
      admin_list_users: {
        Args: Record<PropertyKey, never>;
        Returns: {
          user_id: string
          email: string
          role: Database["public"]["Enums"]["app_role"]
          has_override: boolean
          created_at: string
        }[];
      };
      admin_revoke_user: {
        Args: {
          target: string
        };
        Returns: undefined;
      };
      admin_save_formula_version: {
        Args: {
          p_vid: string
          p_components: Json
          p_lock?: boolean
        };
        Returns: undefined;
      };
      admin_set_user_role: {
        Args: {
          target: string
          new_role: Database["public"]["Enums"]["app_role"]
        };
        Returns: undefined;
      };
      complete_production_order: {
        Args: {
          p_po_id: string
          p_output_lot_code: string
          p_user?: string
        };
        Returns: string;
      };
      convert_qty: {
        Args: {
          p_qty: number
          p_from: Database["public"]["Enums"]["unit_code"]
          p_to: Database["public"]["Enums"]["unit_code"]
          p_density_g_per_ml?: number
        };
        Returns: number;
      };
      create_sales_order: {
        Args: {
          p_code: string
          p_customer_id: string
          p_warehouse_id: string
          p_order_date: string
          p_lines: Json
        };
        Returns: string;
      };
      current_app_role: {
        Args: Record<PropertyKey, never>;
        Returns: Database["public"]["Enums"]["app_role"];
      };
      dashboard_metrics: {
        Args: Record<PropertyKey, never>;
        Returns: Json;
      };
      post_movement: {
        Args: {
          p_lot_id: string
          p_type: Database["public"]["Enums"]["movement_type"]
          p_qty_signed: number
          p_unit: Database["public"]["Enums"]["unit_code"]
          p_reference_type?: string
          p_reference_id?: string
          p_user?: string
        };
        Returns: string;
      };
      product_available_cost: {
        Args: {
          p_product_id: string
        };
        Returns: number;
      };
      production_order_cost: {
        Args: {
          p_po_id: string
        };
        Returns: {
          raw_material_id: string
          sku: string
          name: string
          consumed_quantity: number
          unit: Database["public"]["Enums"]["unit_code"]
          line_cost: number
        }[];
      };
      public_metrics: {
        Args: Record<PropertyKey, never>;
        Returns: Json;
      };
      record_qc: {
        Args: {
          p_lot_id: string
          p_status: Database["public"]["Enums"]["qc_status"]
          p_sg?: number
          p_alcohol?: number
          p_notes?: string
          p_user?: string
        };
        Returns: undefined;
      };
      sales_order_lines_costed: {
        Args: {
          p_order_id: string
        };
        Returns: {
          line_id: string
          product_id: string
          sku: string
          name: string
          quantity: number
          unit: Database["public"]["Enums"]["unit_code"]
          unit_price: number
          est_unit_cost: number
          line_revenue: number
          expected_margin: number
          shipped_quantity: number
          cogs: number
          realized_margin: number
          available_quantity: number
        }[];
      };
      ship_sales_order: {
        Args: {
          p_order_id: string
          p_user?: string
        };
        Returns: undefined;
      };
      ship_sales_order_lines: {
        Args: {
          p_order_id: string
          p_lines: Json
          p_user?: string
        };
        Returns: undefined;
      };
      trace_lot_ancestors: {
        Args: {
          p_lot_id: string
        };
        Returns: {
          lot_id: string
          lot_code: string
          depth: number
          via_order: string
          quantity: number
          unit: Database["public"]["Enums"]["unit_code"]
        }[];
      };
      trace_lot_descendants: {
        Args: {
          p_lot_id: string
        };
        Returns: {
          lot_id: string
          lot_code: string
          depth: number
          via_order: string
          quantity: number
          unit: Database["public"]["Enums"]["unit_code"]
        }[];
      };
    };
    Enums: {
      app_role: "admin" | "production" | "qc" | "viewer";
      formula_basis: "percent" | "mass";
      lot_status: "available" | "quarantine" | "expired" | "consumed" | "rejected";
      material_category: "aroma_chemical" | "essential_oil" | "fixative" | "solvent" | "water" | "packaging";
      movement_type: "receipt" | "issue" | "production_in" | "adjustment" | "shipment";
      production_status: "planned" | "in_progress" | "completed" | "cancelled";
      qc_status: "pending" | "passed" | "failed";
      sales_order_status: "draft" | "confirmed" | "shipped" | "cancelled" | "partially_shipped";
      unit_code: "kg" | "g" | "mg" | "l" | "ml";
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

type PublicSchema = Database['public'];

export type Tables<T extends keyof PublicSchema['Tables']> = PublicSchema['Tables'][T]['Row'];
export type TablesInsert<T extends keyof PublicSchema['Tables']> = PublicSchema['Tables'][T]['Insert'];
export type TablesUpdate<T extends keyof PublicSchema['Tables']> = PublicSchema['Tables'][T]['Update'];
export type Enums<T extends keyof PublicSchema['Enums']> = PublicSchema['Enums'][T];
