// Generated by scripts/gen-types.mjs from the public schema. Do not edit by hand.
// Regenerate after a migration:  yarn gen:types
// (For your live project you can equivalently run:
//   supabase gen types typescript --linked --schema public > src/types/database.ts)

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      app_users: {
        Row: {
          user_id: string
          role: Database["public"]["Enums"]["app_role"]
          created_at: string
        };
        Insert: {
          user_id: string
          role?: Database["public"]["Enums"]["app_role"]
          created_at?: string
        };
        Update: {
          user_id?: string
          role?: Database["public"]["Enums"]["app_role"]
          created_at?: string
        };
        Relationships: [];
      };
      bill_payments: {
        Row: {
          id: string
          bill_id: string
          amount: number
          paid_date: string
          method: string | null
          reference: string | null
          recorded_by: string | null
          recorded_at: string
        };
        Insert: {
          id?: string
          bill_id: string
          amount: number
          paid_date?: string
          method?: string | null
          reference?: string | null
          recorded_by?: string | null
          recorded_at?: string
        };
        Update: {
          id?: string
          bill_id?: string
          amount?: number
          paid_date?: string
          method?: string | null
          reference?: string | null
          recorded_by?: string | null
          recorded_at?: string
        };
        Relationships: [
          {
            foreignKeyName: "bill_payments_bill_id_fkey";
            columns: ["bill_id"];
            isOneToOne: false;
            referencedRelation: "bills";
            referencedColumns: ["id"];
          }
        ];
      };
      bills: {
        Row: {
          id: string
          supplier_id: string
          bill_number: string
          bill_date: string
          due_date: string | null
          amount: number
          description: string | null
          voided_at: string | null
          voided_by: string | null
          void_reason: string | null
          created_by: string | null
          created_at: string
          tax_amount: number
          purchase_order_id: string | null
        };
        Insert: {
          id?: string
          supplier_id: string
          bill_number: string
          bill_date?: string
          due_date?: string | null
          amount: number
          description?: string | null
          voided_at?: string | null
          voided_by?: string | null
          void_reason?: string | null
          created_by?: string | null
          created_at?: string
          tax_amount?: number
          purchase_order_id?: string | null
        };
        Update: {
          id?: string
          supplier_id?: string
          bill_number?: string
          bill_date?: string
          due_date?: string | null
          amount?: number
          description?: string | null
          voided_at?: string | null
          voided_by?: string | null
          void_reason?: string | null
          created_by?: string | null
          created_at?: string
          tax_amount?: number
          purchase_order_id?: string | null
        };
        Relationships: [
          {
            foreignKeyName: "bills_purchase_order_id_fkey";
            columns: ["purchase_order_id"];
            isOneToOne: false;
            referencedRelation: "purchase_orders";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "bills_supplier_id_fkey";
            columns: ["supplier_id"];
            isOneToOne: false;
            referencedRelation: "suppliers";
            referencedColumns: ["id"];
          }
        ];
      };
      costing_settings: {
        Row: {
          id: boolean
          labor_rate_per_hour: number
          overhead_rate: number
          updated_at: string
        };
        Insert: {
          id?: boolean
          labor_rate_per_hour?: number
          overhead_rate?: number
          updated_at?: string
        };
        Update: {
          id?: boolean
          labor_rate_per_hour?: number
          overhead_rate?: number
          updated_at?: string
        };
        Relationships: [];
      };
      credit_allocations: {
        Row: {
          id: string
          credit_note_id: string
          invoice_id: string
          amount: number
          allocated_date: string
          allocated_by: string | null
          created_at: string
        };
        Insert: {
          id?: string
          credit_note_id: string
          invoice_id: string
          amount: number
          allocated_date?: string
          allocated_by?: string | null
          created_at?: string
        };
        Update: {
          id?: string
          credit_note_id?: string
          invoice_id?: string
          amount?: number
          allocated_date?: string
          allocated_by?: string | null
          created_at?: string
        };
        Relationships: [
          {
            foreignKeyName: "credit_allocations_credit_note_id_fkey";
            columns: ["credit_note_id"];
            isOneToOne: false;
            referencedRelation: "issued_documents";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "credit_allocations_invoice_id_fkey";
            columns: ["invoice_id"];
            isOneToOne: false;
            referencedRelation: "issued_documents";
            referencedColumns: ["id"];
          }
        ];
      };
      credit_note_lines: {
        Row: {
          id: string
          credit_note_id: string
          sales_order_line_id: string
          product_id: string
          quantity: number
          unit: Database["public"]["Enums"]["unit_code"]
          unit_price: number
          cogs_reversed: number
        };
        Insert: {
          id?: string
          credit_note_id: string
          sales_order_line_id: string
          product_id: string
          quantity: number
          unit: Database["public"]["Enums"]["unit_code"]
          unit_price?: number
          cogs_reversed?: number
        };
        Update: {
          id?: string
          credit_note_id?: string
          sales_order_line_id?: string
          product_id?: string
          quantity?: number
          unit?: Database["public"]["Enums"]["unit_code"]
          unit_price?: number
          cogs_reversed?: number
        };
        Relationships: [
          {
            foreignKeyName: "credit_note_lines_credit_note_id_fkey";
            columns: ["credit_note_id"];
            isOneToOne: false;
            referencedRelation: "credit_notes";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "credit_note_lines_product_id_fkey";
            columns: ["product_id"];
            isOneToOne: false;
            referencedRelation: "products";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "credit_note_lines_sales_order_line_id_fkey";
            columns: ["sales_order_line_id"];
            isOneToOne: false;
            referencedRelation: "sales_order_lines";
            referencedColumns: ["id"];
          }
        ];
      };
      credit_notes: {
        Row: {
          id: string
          code: string
          sales_order_id: string
          credit_date: string
          created_at: string
        };
        Insert: {
          id?: string
          code: string
          sales_order_id: string
          credit_date?: string
          created_at?: string
        };
        Update: {
          id?: string
          code?: string
          sales_order_id?: string
          credit_date?: string
          created_at?: string
        };
        Relationships: [
          {
            foreignKeyName: "credit_notes_sales_order_id_fkey";
            columns: ["sales_order_id"];
            isOneToOne: false;
            referencedRelation: "sales_orders";
            referencedColumns: ["id"];
          }
        ];
      };
      customer_receipts: {
        Row: {
          id: string
          customer_id: string
          receipt_date: string
          amount: number
          method: string | null
          reference: string | null
          recorded_by: string | null
          recorded_at: string
        };
        Insert: {
          id?: string
          customer_id: string
          receipt_date?: string
          amount: number
          method?: string | null
          reference?: string | null
          recorded_by?: string | null
          recorded_at?: string
        };
        Update: {
          id?: string
          customer_id?: string
          receipt_date?: string
          amount?: number
          method?: string | null
          reference?: string | null
          recorded_by?: string | null
          recorded_at?: string
        };
        Relationships: [
          {
            foreignKeyName: "customer_receipts_customer_id_fkey";
            columns: ["customer_id"];
            isOneToOne: false;
            referencedRelation: "customers";
            referencedColumns: ["id"];
          }
        ];
      };
      customers: {
        Row: {
          id: string
          code: string
          name: string
          email: string | null
          phone: string | null
          address: string | null
          created_at: string
          payment_terms_days: number
          tax_exempt: boolean
          discount_pct: number
          tax_id: string | null
        };
        Insert: {
          id?: string
          code: string
          name: string
          email?: string | null
          phone?: string | null
          address?: string | null
          created_at?: string
          payment_terms_days?: number
          tax_exempt?: boolean
          discount_pct?: number
          tax_id?: string | null
        };
        Update: {
          id?: string
          code?: string
          name?: string
          email?: string | null
          phone?: string | null
          address?: string | null
          created_at?: string
          payment_terms_days?: number
          tax_exempt?: boolean
          discount_pct?: number
          tax_id?: string | null
        };
        Relationships: [];
      };
      document_emails: {
        Row: {
          id: string
          issued_document_id: string
          recipient: string
          subject: string
          message: string
          sent_by: string | null
          sent_at: string
        };
        Insert: {
          id?: string
          issued_document_id: string
          recipient: string
          subject: string
          message: string
          sent_by?: string | null
          sent_at?: string
        };
        Update: {
          id?: string
          issued_document_id?: string
          recipient?: string
          subject?: string
          message?: string
          sent_by?: string | null
          sent_at?: string
        };
        Relationships: [
          {
            foreignKeyName: "document_emails_issued_document_id_fkey";
            columns: ["issued_document_id"];
            isOneToOne: false;
            referencedRelation: "issued_documents";
            referencedColumns: ["id"];
          }
        ];
      };
      document_sequences: {
        Row: {
          kind: string
          year: number
          next_value: number
        };
        Insert: {
          kind: string
          year: number
          next_value?: number
        };
        Update: {
          kind?: string
          year?: number
          next_value?: number
        };
        Relationships: [];
      };
      formula_components: {
        Row: {
          id: string
          formula_version_id: string
          raw_material_id: string
          quantity: number
          unit: Database["public"]["Enums"]["unit_code"]
          sequence: number
        };
        Insert: {
          id?: string
          formula_version_id: string
          raw_material_id: string
          quantity: number
          unit: Database["public"]["Enums"]["unit_code"]
          sequence?: number
        };
        Update: {
          id?: string
          formula_version_id?: string
          raw_material_id?: string
          quantity?: number
          unit?: Database["public"]["Enums"]["unit_code"]
          sequence?: number
        };
        Relationships: [
          {
            foreignKeyName: "formula_components_formula_version_id_fkey";
            columns: ["formula_version_id"];
            isOneToOne: false;
            referencedRelation: "formula_versions";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "formula_components_raw_material_id_fkey";
            columns: ["raw_material_id"];
            isOneToOne: false;
            referencedRelation: "raw_materials";
            referencedColumns: ["id"];
          }
        ];
      };
      formula_versions: {
        Row: {
          id: string
          formula_id: string
          version_no: number
          basis: Database["public"]["Enums"]["formula_basis"]
          is_locked: boolean
          created_at: string
        };
        Insert: {
          id?: string
          formula_id: string
          version_no: number
          basis: Database["public"]["Enums"]["formula_basis"]
          is_locked?: boolean
          created_at?: string
        };
        Update: {
          id?: string
          formula_id?: string
          version_no?: number
          basis?: Database["public"]["Enums"]["formula_basis"]
          is_locked?: boolean
          created_at?: string
        };
        Relationships: [
          {
            foreignKeyName: "formula_versions_formula_id_fkey";
            columns: ["formula_id"];
            isOneToOne: false;
            referencedRelation: "formulas";
            referencedColumns: ["id"];
          }
        ];
      };
      formulas: {
        Row: {
          id: string
          code: string
          name: string
          product_id: string | null
          created_at: string
        };
        Insert: {
          id?: string
          code: string
          name: string
          product_id?: string | null
          created_at?: string
        };
        Update: {
          id?: string
          code?: string
          name?: string
          product_id?: string | null
          created_at?: string
        };
        Relationships: [
          {
            foreignKeyName: "formulas_product_id_fkey";
            columns: ["product_id"];
            isOneToOne: false;
            referencedRelation: "products";
            referencedColumns: ["id"];
          }
        ];
      };
      inventory_lots: {
        Row: {
          id: string
          lot_code: string
          item_type: string
          raw_material_id: string | null
          product_id: string | null
          warehouse_id: string
          quantity_on_hand: number
          unit: Database["public"]["Enums"]["unit_code"]
          status: Database["public"]["Enums"]["lot_status"]
          expiry_date: string | null
          received_at: string
          unit_cost: number | null
        };
        Insert: {
          id?: string
          lot_code: string
          item_type: string
          raw_material_id?: string | null
          product_id?: string | null
          warehouse_id: string
          quantity_on_hand?: number
          unit: Database["public"]["Enums"]["unit_code"]
          status?: Database["public"]["Enums"]["lot_status"]
          expiry_date?: string | null
          received_at?: string
          unit_cost?: number | null
        };
        Update: {
          id?: string
          lot_code?: string
          item_type?: string
          raw_material_id?: string | null
          product_id?: string | null
          warehouse_id?: string
          quantity_on_hand?: number
          unit?: Database["public"]["Enums"]["unit_code"]
          status?: Database["public"]["Enums"]["lot_status"]
          expiry_date?: string | null
          received_at?: string
          unit_cost?: number | null
        };
        Relationships: [
          {
            foreignKeyName: "inventory_lots_product_id_fkey";
            columns: ["product_id"];
            isOneToOne: false;
            referencedRelation: "products";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "inventory_lots_raw_material_id_fkey";
            columns: ["raw_material_id"];
            isOneToOne: false;
            referencedRelation: "raw_materials";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "inventory_lots_warehouse_id_fkey";
            columns: ["warehouse_id"];
            isOneToOne: false;
            referencedRelation: "warehouses";
            referencedColumns: ["id"];
          }
        ];
      };
      invoice_payments: {
        Row: {
          id: string
          issued_document_id: string
          amount: number
          paid_date: string
          method: string | null
          reference: string | null
          recorded_by: string | null
          recorded_at: string
          receipt_id: string | null
        };
        Insert: {
          id?: string
          issued_document_id: string
          amount: number
          paid_date?: string
          method?: string | null
          reference?: string | null
          recorded_by?: string | null
          recorded_at?: string
          receipt_id?: string | null
        };
        Update: {
          id?: string
          issued_document_id?: string
          amount?: number
          paid_date?: string
          method?: string | null
          reference?: string | null
          recorded_by?: string | null
          recorded_at?: string
          receipt_id?: string | null
        };
        Relationships: [
          {
            foreignKeyName: "invoice_payments_issued_document_id_fkey";
            columns: ["issued_document_id"];
            isOneToOne: false;
            referencedRelation: "issued_documents";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "invoice_payments_receipt_id_fkey";
            columns: ["receipt_id"];
            isOneToOne: false;
            referencedRelation: "customer_receipts";
            referencedColumns: ["id"];
          }
        ];
      };
      issued_documents: {
        Row: {
          id: string
          kind: string
          sales_order_id: string
          credit_note_id: string | null
          document_number: string
          snapshot: Json
          issued_by: string | null
          issued_at: string
          total: number | null
          voided_at: string | null
          voided_by: string | null
          void_reason: string | null
          due_date: string | null
        };
        Insert: {
          id?: string
          kind: string
          sales_order_id: string
          credit_note_id?: string | null
          document_number: string
          snapshot: Json
          issued_by?: string | null
          issued_at?: string
          total?: number | null
          voided_at?: string | null
          voided_by?: string | null
          void_reason?: string | null
          due_date?: string | null
        };
        Update: {
          id?: string
          kind?: string
          sales_order_id?: string
          credit_note_id?: string | null
          document_number?: string
          snapshot?: Json
          issued_by?: string | null
          issued_at?: string
          total?: number | null
          voided_at?: string | null
          voided_by?: string | null
          void_reason?: string | null
          due_date?: string | null
        };
        Relationships: [
          {
            foreignKeyName: "issued_documents_credit_note_id_fkey";
            columns: ["credit_note_id"];
            isOneToOne: false;
            referencedRelation: "credit_notes";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "issued_documents_sales_order_id_fkey";
            columns: ["sales_order_id"];
            isOneToOne: false;
            referencedRelation: "sales_orders";
            referencedColumns: ["id"];
          }
        ];
      };
      lot_genealogy: {
        Row: {
          id: string
          parent_lot_id: string
          child_lot_id: string
          production_order_id: string
          quantity: number
          unit: Database["public"]["Enums"]["unit_code"]
          created_at: string
        };
        Insert: {
          id?: string
          parent_lot_id: string
          child_lot_id: string
          production_order_id: string
          quantity: number
          unit: Database["public"]["Enums"]["unit_code"]
          created_at?: string
        };
        Update: {
          id?: string
          parent_lot_id?: string
          child_lot_id?: string
          production_order_id?: string
          quantity?: number
          unit?: Database["public"]["Enums"]["unit_code"]
          created_at?: string
        };
        Relationships: [
          {
            foreignKeyName: "lot_genealogy_child_lot_id_fkey";
            columns: ["child_lot_id"];
            isOneToOne: false;
            referencedRelation: "inventory_lots";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "lot_genealogy_parent_lot_id_fkey";
            columns: ["parent_lot_id"];
            isOneToOne: false;
            referencedRelation: "inventory_lots";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "lot_genealogy_production_order_id_fkey";
            columns: ["production_order_id"];
            isOneToOne: false;
            referencedRelation: "production_orders";
            referencedColumns: ["id"];
          }
        ];
      };
      product_costing_rates: {
        Row: {
          product_id: string
          labor_rate_per_hour: number | null
          overhead_rate: number | null
          updated_at: string
        };
        Insert: {
          product_id: string
          labor_rate_per_hour?: number | null
          overhead_rate?: number | null
          updated_at?: string
        };
        Update: {
          product_id?: string
          labor_rate_per_hour?: number | null
          overhead_rate?: number | null
          updated_at?: string
        };
        Relationships: [
          {
            foreignKeyName: "product_costing_rates_product_id_fkey";
            columns: ["product_id"];
            isOneToOne: true;
            referencedRelation: "products";
            referencedColumns: ["id"];
          }
        ];
      };
      production_consumptions: {
        Row: {
          id: string
          production_order_id: string
          lot_id: string
          raw_material_id: string
          quantity: number
          unit: Database["public"]["Enums"]["unit_code"]
          cost: number | null
        };
        Insert: {
          id?: string
          production_order_id: string
          lot_id: string
          raw_material_id: string
          quantity: number
          unit: Database["public"]["Enums"]["unit_code"]
          cost?: number | null
        };
        Update: {
          id?: string
          production_order_id?: string
          lot_id?: string
          raw_material_id?: string
          quantity?: number
          unit?: Database["public"]["Enums"]["unit_code"]
          cost?: number | null
        };
        Relationships: [
          {
            foreignKeyName: "production_consumptions_lot_id_fkey";
            columns: ["lot_id"];
            isOneToOne: false;
            referencedRelation: "inventory_lots";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "production_consumptions_production_order_id_fkey";
            columns: ["production_order_id"];
            isOneToOne: false;
            referencedRelation: "production_orders";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "production_consumptions_raw_material_id_fkey";
            columns: ["raw_material_id"];
            isOneToOne: false;
            referencedRelation: "raw_materials";
            referencedColumns: ["id"];
          }
        ];
      };
      production_halal_overrides: {
        Row: {
          id: string
          production_order_id: string
          formula_version_id: string
          reason: string
          noncompliance: Json
          overridden_by: string | null
          overridden_at: string
        };
        Insert: {
          id?: string
          production_order_id: string
          formula_version_id: string
          reason: string
          noncompliance?: Json
          overridden_by?: string | null
          overridden_at?: string
        };
        Update: {
          id?: string
          production_order_id?: string
          formula_version_id?: string
          reason?: string
          noncompliance?: Json
          overridden_by?: string | null
          overridden_at?: string
        };
        Relationships: [
          {
            foreignKeyName: "production_halal_overrides_formula_version_id_fkey";
            columns: ["formula_version_id"];
            isOneToOne: false;
            referencedRelation: "formula_versions";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "production_halal_overrides_production_order_id_fkey";
            columns: ["production_order_id"];
            isOneToOne: false;
            referencedRelation: "production_orders";
            referencedColumns: ["id"];
          }
        ];
      };
      production_order_components: {
        Row: {
          id: string
          production_order_id: string
          raw_material_id: string
          planned_quantity: number
          unit: Database["public"]["Enums"]["unit_code"]
        };
        Insert: {
          id?: string
          production_order_id: string
          raw_material_id: string
          planned_quantity: number
          unit: Database["public"]["Enums"]["unit_code"]
        };
        Update: {
          id?: string
          production_order_id?: string
          raw_material_id?: string
          planned_quantity?: number
          unit?: Database["public"]["Enums"]["unit_code"]
        };
        Relationships: [
          {
            foreignKeyName: "production_order_components_production_order_id_fkey";
            columns: ["production_order_id"];
            isOneToOne: false;
            referencedRelation: "production_orders";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "production_order_components_raw_material_id_fkey";
            columns: ["raw_material_id"];
            isOneToOne: false;
            referencedRelation: "raw_materials";
            referencedColumns: ["id"];
          }
        ];
      };
      production_orders: {
        Row: {
          id: string
          code: string
          product_id: string
          formula_version_id: string
          warehouse_id: string
          planned_quantity: number
          unit: Database["public"]["Enums"]["unit_code"]
          status: Database["public"]["Enums"]["production_status"]
          output_lot_id: string | null
          created_at: string
          completed_at: string | null
          labor_hours: number
          material_cost: number | null
          labor_cost: number | null
          overhead_cost: number | null
        };
        Insert: {
          id?: string
          code: string
          product_id: string
          formula_version_id: string
          warehouse_id: string
          planned_quantity: number
          unit: Database["public"]["Enums"]["unit_code"]
          status?: Database["public"]["Enums"]["production_status"]
          output_lot_id?: string | null
          created_at?: string
          completed_at?: string | null
          labor_hours?: number
          material_cost?: number | null
          labor_cost?: number | null
          overhead_cost?: number | null
        };
        Update: {
          id?: string
          code?: string
          product_id?: string
          formula_version_id?: string
          warehouse_id?: string
          planned_quantity?: number
          unit?: Database["public"]["Enums"]["unit_code"]
          status?: Database["public"]["Enums"]["production_status"]
          output_lot_id?: string | null
          created_at?: string
          completed_at?: string | null
          labor_hours?: number
          material_cost?: number | null
          labor_cost?: number | null
          overhead_cost?: number | null
        };
        Relationships: [
          {
            foreignKeyName: "production_orders_formula_version_id_fkey";
            columns: ["formula_version_id"];
            isOneToOne: false;
            referencedRelation: "formula_versions";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "production_orders_output_lot_id_fkey";
            columns: ["output_lot_id"];
            isOneToOne: false;
            referencedRelation: "inventory_lots";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "production_orders_product_id_fkey";
            columns: ["product_id"];
            isOneToOne: false;
            referencedRelation: "products";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "production_orders_warehouse_id_fkey";
            columns: ["warehouse_id"];
            isOneToOne: false;
            referencedRelation: "warehouses";
            referencedColumns: ["id"];
          }
        ];
      };
      products: {
        Row: {
          id: string
          sku: string
          name: string
          base_unit: Database["public"]["Enums"]["unit_code"]
          created_at: string
        };
        Insert: {
          id?: string
          sku: string
          name: string
          base_unit: Database["public"]["Enums"]["unit_code"]
          created_at?: string
        };
        Update: {
          id?: string
          sku?: string
          name?: string
          base_unit?: Database["public"]["Enums"]["unit_code"]
          created_at?: string
        };
        Relationships: [];
      };
      purchase_order_lines: {
        Row: {
          id: string
          purchase_order_id: string
          line_no: number
          raw_material_id: string
          quantity: number
          unit: Database["public"]["Enums"]["unit_code"]
          unit_cost: number
          received_quantity: number
        };
        Insert: {
          id?: string
          purchase_order_id: string
          line_no: number
          raw_material_id: string
          quantity: number
          unit: Database["public"]["Enums"]["unit_code"]
          unit_cost: number
          received_quantity?: number
        };
        Update: {
          id?: string
          purchase_order_id?: string
          line_no?: number
          raw_material_id?: string
          quantity?: number
          unit?: Database["public"]["Enums"]["unit_code"]
          unit_cost?: number
          received_quantity?: number
        };
        Relationships: [
          {
            foreignKeyName: "purchase_order_lines_purchase_order_id_fkey";
            columns: ["purchase_order_id"];
            isOneToOne: false;
            referencedRelation: "purchase_orders";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "purchase_order_lines_raw_material_id_fkey";
            columns: ["raw_material_id"];
            isOneToOne: false;
            referencedRelation: "raw_materials";
            referencedColumns: ["id"];
          }
        ];
      };
      purchase_orders: {
        Row: {
          id: string
          code: string
          supplier_id: string
          warehouse_id: string
          order_date: string
          status: string
          note: string | null
          created_by: string | null
          created_at: string
        };
        Insert: {
          id?: string
          code: string
          supplier_id: string
          warehouse_id: string
          order_date?: string
          status?: string
          note?: string | null
          created_by?: string | null
          created_at?: string
        };
        Update: {
          id?: string
          code?: string
          supplier_id?: string
          warehouse_id?: string
          order_date?: string
          status?: string
          note?: string | null
          created_by?: string | null
          created_at?: string
        };
        Relationships: [
          {
            foreignKeyName: "purchase_orders_supplier_id_fkey";
            columns: ["supplier_id"];
            isOneToOne: false;
            referencedRelation: "suppliers";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "purchase_orders_warehouse_id_fkey";
            columns: ["warehouse_id"];
            isOneToOne: false;
            referencedRelation: "warehouses";
            referencedColumns: ["id"];
          }
        ];
      };
      qc_checks: {
        Row: {
          id: string
          lot_id: string
          production_order_id: string | null
          status: Database["public"]["Enums"]["qc_status"]
          specific_gravity: number | null
          alcohol_pct: number | null
          notes: string | null
          checked_by: string | null
          checked_at: string | null
        };
        Insert: {
          id?: string
          lot_id: string
          production_order_id?: string | null
          status?: Database["public"]["Enums"]["qc_status"]
          specific_gravity?: number | null
          alcohol_pct?: number | null
          notes?: string | null
          checked_by?: string | null
          checked_at?: string | null
        };
        Update: {
          id?: string
          lot_id?: string
          production_order_id?: string | null
          status?: Database["public"]["Enums"]["qc_status"]
          specific_gravity?: number | null
          alcohol_pct?: number | null
          notes?: string | null
          checked_by?: string | null
          checked_at?: string | null
        };
        Relationships: [
          {
            foreignKeyName: "qc_checks_lot_id_fkey";
            columns: ["lot_id"];
            isOneToOne: false;
            referencedRelation: "inventory_lots";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "qc_checks_production_order_id_fkey";
            columns: ["production_order_id"];
            isOneToOne: false;
            referencedRelation: "production_orders";
            referencedColumns: ["id"];
          }
        ];
      };
      raw_materials: {
        Row: {
          id: string
          sku: string
          name: string
          category: Database["public"]["Enums"]["material_category"]
          base_unit: Database["public"]["Enums"]["unit_code"]
          density_g_per_ml: number | null
          standard_cost: number
          is_flammable: boolean
          created_at: string
          halal_status: Database["public"]["Enums"]["halal_status"]
          halal_cert_number: string | null
          halal_certifier: string | null
          halal_cert_expiry: string | null
        };
        Insert: {
          id?: string
          sku: string
          name: string
          category: Database["public"]["Enums"]["material_category"]
          base_unit: Database["public"]["Enums"]["unit_code"]
          density_g_per_ml?: number | null
          standard_cost?: number
          is_flammable?: boolean
          created_at?: string
          halal_status?: Database["public"]["Enums"]["halal_status"]
          halal_cert_number?: string | null
          halal_certifier?: string | null
          halal_cert_expiry?: string | null
        };
        Update: {
          id?: string
          sku?: string
          name?: string
          category?: Database["public"]["Enums"]["material_category"]
          base_unit?: Database["public"]["Enums"]["unit_code"]
          density_g_per_ml?: number | null
          standard_cost?: number
          is_flammable?: boolean
          created_at?: string
          halal_status?: Database["public"]["Enums"]["halal_status"]
          halal_cert_number?: string | null
          halal_certifier?: string | null
          halal_cert_expiry?: string | null
        };
        Relationships: [];
      };
      sales_order_lines: {
        Row: {
          id: string
          sales_order_id: string
          product_id: string
          quantity: number
          unit: Database["public"]["Enums"]["unit_code"]
          unit_price: number
          shipped_quantity: number
          cogs: number | null
          returned_quantity: number
        };
        Insert: {
          id?: string
          sales_order_id: string
          product_id: string
          quantity: number
          unit: Database["public"]["Enums"]["unit_code"]
          unit_price?: number
          shipped_quantity?: number
          cogs?: number | null
          returned_quantity?: number
        };
        Update: {
          id?: string
          sales_order_id?: string
          product_id?: string
          quantity?: number
          unit?: Database["public"]["Enums"]["unit_code"]
          unit_price?: number
          shipped_quantity?: number
          cogs?: number | null
          returned_quantity?: number
        };
        Relationships: [
          {
            foreignKeyName: "sales_order_lines_product_id_fkey";
            columns: ["product_id"];
            isOneToOne: false;
            referencedRelation: "products";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "sales_order_lines_sales_order_id_fkey";
            columns: ["sales_order_id"];
            isOneToOne: false;
            referencedRelation: "sales_orders";
            referencedColumns: ["id"];
          }
        ];
      };
      sales_orders: {
        Row: {
          id: string
          code: string
          customer_id: string
          warehouse_id: string
          status: Database["public"]["Enums"]["sales_order_status"]
          order_date: string
          created_at: string
        };
        Insert: {
          id?: string
          code: string
          customer_id: string
          warehouse_id: string
          status?: Database["public"]["Enums"]["sales_order_status"]
          order_date?: string
          created_at?: string
        };
        Update: {
          id?: string
          code?: string
          customer_id?: string
          warehouse_id?: string
          status?: Database["public"]["Enums"]["sales_order_status"]
          order_date?: string
          created_at?: string
        };
        Relationships: [
          {
            foreignKeyName: "sales_orders_customer_id_fkey";
            columns: ["customer_id"];
            isOneToOne: false;
            referencedRelation: "customers";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "sales_orders_warehouse_id_fkey";
            columns: ["warehouse_id"];
            isOneToOne: false;
            referencedRelation: "warehouses";
            referencedColumns: ["id"];
          }
        ];
      };
      statement_emails: {
        Row: {
          id: string
          customer_id: string
          period_start: string
          period_end: string
          recipient: string
          subject: string
          sent_by: string | null
          sent_at: string
        };
        Insert: {
          id?: string
          customer_id: string
          period_start: string
          period_end: string
          recipient: string
          subject: string
          sent_by?: string | null
          sent_at?: string
        };
        Update: {
          id?: string
          customer_id?: string
          period_start?: string
          period_end?: string
          recipient?: string
          subject?: string
          sent_by?: string | null
          sent_at?: string
        };
        Relationships: [
          {
            foreignKeyName: "statement_emails_customer_id_fkey";
            columns: ["customer_id"];
            isOneToOne: false;
            referencedRelation: "customers";
            referencedColumns: ["id"];
          }
        ];
      };
      stock_movements: {
        Row: {
          id: string
          lot_id: string
          movement_type: Database["public"]["Enums"]["movement_type"]
          quantity: number
          unit: Database["public"]["Enums"]["unit_code"]
          reference_type: string | null
          reference_id: string | null
          created_by: string | null
          created_at: string
        };
        Insert: {
          id?: string
          lot_id: string
          movement_type: Database["public"]["Enums"]["movement_type"]
          quantity: number
          unit: Database["public"]["Enums"]["unit_code"]
          reference_type?: string | null
          reference_id?: string | null
          created_by?: string | null
          created_at?: string
        };
        Update: {
          id?: string
          lot_id?: string
          movement_type?: Database["public"]["Enums"]["movement_type"]
          quantity?: number
          unit?: Database["public"]["Enums"]["unit_code"]
          reference_type?: string | null
          reference_id?: string | null
          created_by?: string | null
          created_at?: string
        };
        Relationships: [
          {
            foreignKeyName: "stock_movements_lot_id_fkey";
            columns: ["lot_id"];
            isOneToOne: false;
            referencedRelation: "inventory_lots";
            referencedColumns: ["id"];
          }
        ];
      };
      suppliers: {
        Row: {
          id: string
          code: string
          name: string
          email: string | null
          phone: string | null
          address: string | null
          payment_terms_days: number
          created_at: string
          tax_id: string | null
        };
        Insert: {
          id?: string
          code: string
          name: string
          email?: string | null
          phone?: string | null
          address?: string | null
          payment_terms_days?: number
          created_at?: string
          tax_id?: string | null
        };
        Update: {
          id?: string
          code?: string
          name?: string
          email?: string | null
          phone?: string | null
          address?: string | null
          payment_terms_days?: number
          created_at?: string
          tax_id?: string | null
        };
        Relationships: [];
      };
      tax_settings: {
        Row: {
          id: boolean
          ppn_rate: number
          updated_at: string
        };
        Insert: {
          id?: boolean
          ppn_rate?: number
          updated_at?: string
        };
        Update: {
          id?: boolean
          ppn_rate?: number
          updated_at?: string
        };
        Relationships: [];
      };
      warehouses: {
        Row: {
          id: string
          code: string
          name: string
          created_at: string
        };
        Insert: {
          id?: string
          code: string
          name: string
          created_at?: string
        };
        Update: {
          id?: string
          code?: string
          name?: string
          created_at?: string
        };
        Relationships: [];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      _create_lot: {
        Args: {
          p_lot_code: string
          p_item_type: string
          p_raw_material_id: string
          p_product_id: string
          p_warehouse_id: string
          p_unit: Database["public"]["Enums"]["unit_code"]
          p_status?: Database["public"]["Enums"]["lot_status"]
          p_unit_cost?: number
        };
        Returns: string;
      };
      _restock_returned_lot: {
        Args: {
          p_product_id: string
          p_warehouse_id: string
          p_lot_code: string
          p_qty: number
          p_unit: Database["public"]["Enums"]["unit_code"]
          p_unit_cost: number
          p_credit_note_id: string
          p_user: string
        };
        Returns: string;
      };
      _ship_order_line: {
        Args: {
          p_line_id: string
          p_warehouse_id: string
          p_target: number
          p_strict: boolean
          p_user: string
        };
        Returns: number;
      };
      admin_check_user_deletable: {
        Args: {
          p_user_id: string
        };
        Returns: string;
      };
      admin_create_formula_version: {
        Args: {
          p_formula_id: string
          p_basis: Database["public"]["Enums"]["formula_basis"]
          p_clone_from?: string
        };
        Returns: string;
      };
      admin_delete_formula_version: {
        Args: {
          p_vid: string
        };
        Returns: undefined;
      };
      admin_list_users: {
        Args: Record<PropertyKey, never>;
        Returns: {
          user_id: string
          email: string
          role: Database["public"]["Enums"]["app_role"]
          has_override: boolean
          created_at: string
        }[];
      };
      admin_revoke_user: {
        Args: {
          target: string
        };
        Returns: undefined;
      };
      admin_save_formula_version: {
        Args: {
          p_vid: string
          p_components: Json
          p_lock?: boolean
        };
        Returns: undefined;
      };
      admin_set_user_role: {
        Args: {
          target: string
          new_role: Database["public"]["Enums"]["app_role"]
        };
        Returns: undefined;
      };
      allocate_credit_note: {
        Args: {
          p_credit_note_id: string
          p_invoice_id: string
          p_amount: number
          p_allocated_date?: string
        };
        Returns: string;
      };
      apply_customer_receipt: {
        Args: {
          p_customer_id: string
          p_receipt_date: string
          p_amount: number
          p_method: string
          p_reference: string
          p_allocations: Json
        };
        Returns: string;
      };
      apply_receipt: {
        Args: {
          p_receipt_id: string
          p_allocations: Json
        };
        Returns: undefined;
      };
      bill_payables: {
        Args: {
          p_supplier_id?: string
        };
        Returns: {
          bill_id: string
          bill_number: string
          supplier_id: string
          supplier_name: string
          bill_date: string
          due_date: string
          amount: number
          paid: number
          open: number
          status: string
          overdue: boolean
          payment_count: number
          last_paid_date: string
          void_reason: string
        }[];
      };
      bill_purchase_order: {
        Args: {
          p_po_id: string
          p_bill_number: string
          p_bill_date: string
          p_amount?: number
          p_due_date?: string
          p_description?: string
          p_tax_amount?: number
        };
        Returns: string;
      };
      cancel_purchase_order: {
        Args: {
          p_po_id: string
        };
        Returns: undefined;
      };
      complete_production_order: {
        Args: {
          p_po_id: string
          p_output_lot_code: string
          p_user?: string
          p_labor_hours?: number
          p_halal_override?: boolean
          p_override_reason?: string
        };
        Returns: string;
      };
      convert_qty: {
        Args: {
          p_qty: number
          p_from: Database["public"]["Enums"]["unit_code"]
          p_to: Database["public"]["Enums"]["unit_code"]
          p_density_g_per_ml?: number
        };
        Returns: number;
      };
      create_bill: {
        Args: {
          p_supplier_id: string
          p_bill_number: string
          p_bill_date: string
          p_amount: number
          p_due_date?: string
          p_description?: string
          p_tax_amount?: number
        };
        Returns: string;
      };
      create_purchase_order: {
        Args: {
          p_code: string
          p_supplier_id: string
          p_warehouse_id: string
          p_order_date: string
          p_lines: Json
        };
        Returns: string;
      };
      create_return: {
        Args: {
          p_order_id: string
          p_code: string
          p_lines: Json
          p_user?: string
        };
        Returns: string;
      };
      create_sales_order: {
        Args: {
          p_code: string
          p_customer_id: string
          p_warehouse_id: string
          p_order_date: string
          p_lines: Json
        };
        Returns: string;
      };
      credit_allocations_view: {
        Args: {
          p_order_id?: string
        };
        Returns: {
          allocation_id: string
          amount: number
          allocated_date: string
          invoice_id: string
          invoice_number: string
          invoice_order_id: string
          credit_note_id: string
          credit_note_number: string
          credit_note_order_id: string
        }[];
      };
      credit_note_balances: {
        Args: {
          p_order_id?: string
          p_customer_id?: string
        };
        Returns: {
          issued_document_id: string
          document_number: string
          sales_order_id: string
          order_code: string
          customer_id: string
          customer_name: string
          issued_at: string
          total: number
          allocated: number
          remaining: number
          voided: boolean
        }[];
      };
      credit_note_document: {
        Args: {
          p_credit_note_id: string
        };
        Returns: Json;
      };
      current_app_role: {
        Args: Record<PropertyKey, never>;
        Returns: Database["public"]["Enums"]["app_role"];
      };
      customer_ledger: {
        Args: {
          p_customer_id: string
          p_start: string
          p_end: string
        };
        Returns: {
          entry_date: string
          entry_type: string
          reference: string
          debit: number
          credit: number
          balance: number
        }[];
      };
      customer_open_invoices: {
        Args: {
          p_customer_id: string
        };
        Returns: {
          issued_document_id: string
          document_number: string
          issued_at: string
          due_date: string
          total: number
          paid: number
          allocated: number
          open: number
          status: string
          overdue: boolean
        }[];
      };
      dashboard_metrics: {
        Args: Record<PropertyKey, never>;
        Returns: Json;
      };
      delete_bill_payment: {
        Args: {
          p_id: string
        };
        Returns: undefined;
      };
      delete_credit_allocation: {
        Args: {
          p_id: string
        };
        Returns: undefined;
      };
      delete_invoice_payment: {
        Args: {
          p_id: string
        };
        Returns: undefined;
      };
      delete_receipt: {
        Args: {
          p_id: string
        };
        Returns: undefined;
      };
      effective_costing_rates: {
        Args: {
          p_product_id: string
        };
        Returns: {
          labor_rate_per_hour: number
          overhead_rate: number
        }[];
      };
      email_history: {
        Args: Record<PropertyKey, never>;
        Returns: {
          sent_at: string
          kind: string
          doc_kind: string
          reference: string
          party_name: string
          recipient: string
          subject: string
        }[];
      };
      fefo_allocate: {
        Args: {
          p_item_type: string
          p_raw_material_id: string
          p_product_id: string
          p_warehouse_id: string
          p_qty: number
          p_unit: Database["public"]["Enums"]["unit_code"]
        };
        Returns: {
          lot_id: string
          take_qty: number
          lot_unit: Database["public"]["Enums"]["unit_code"]
          lot_unit_cost: number
        }[];
      };
      formula_version_halal_noncompliance: {
        Args: {
          p_formula_version_id: string
          p_as_of?: string
        };
        Returns: {
          raw_material_id: string
          sku: string
          name: string
          halal_status: Database["public"]["Enums"]["halal_status"]
          halal_cert_number: string
          halal_cert_expiry: string
          reason: string
        }[];
      };
      formula_versions_compliance: {
        Args: {
          p_as_of?: string
        };
        Returns: {
          formula_version_id: string
          formula_code: string
          formula_name: string
          product_name: string
          version_no: number
          is_locked: boolean
          compliant: boolean
          offending: Json
        }[];
      };
      invoice_document: {
        Args: {
          p_order_id: string
        };
        Returns: Json;
      };
      invoice_receivables: {
        Args: {
          p_order_id?: string
        };
        Returns: {
          issued_document_id: string
          document_number: string
          sales_order_id: string
          order_code: string
          customer_name: string
          issued_at: string
          due_date: string
          total: number
          paid: number
          allocated: number
          open: number
          status: string
          overdue: boolean
          payment_count: number
          last_paid_date: string
          void_reason: string
        }[];
      };
      is_formula_version_halal: {
        Args: {
          p_formula_version_id: string
          p_as_of?: string
        };
        Returns: boolean;
      };
      issue_document: {
        Args: {
          p_kind: string
          p_order_id?: string
          p_credit_note_id?: string
        };
        Returns: string;
      };
      issued_documents_register: {
        Args: Record<PropertyKey, never>;
        Returns: {
          issued_document_id: string
          kind: string
          document_number: string
          sales_order_id: string
          order_code: string
          customer_name: string
          issued_at: string
          total: number
          voided: boolean
          void_reason: string
          email_count: number
          last_emailed_at: string
          last_recipient: string
          payment_status: string
          paid: number
          open: number
        }[];
      };
      list_customer_receipts: {
        Args: {
          p_customer_id?: string
        };
        Returns: {
          receipt_id: string
          customer_id: string
          customer_name: string
          receipt_date: string
          amount: number
          applied: number
          unapplied: number
          application_count: number
          method: string
          reference: string
        }[];
      };
      next_document_number: {
        Args: {
          p_kind: string
          p_as_of?: string
        };
        Returns: string;
      };
      packing_slip_document: {
        Args: {
          p_order_id: string
        };
        Returns: Json;
      };
      payables_aging: {
        Args: {
          p_as_of?: string
        };
        Returns: {
          supplier_id: string
          supplier_name: string
          bill_id: string
          bill_number: string
          bill_date: string
          due_date: string
          days_overdue: number
          bucket: string
          amount: number
          paid: number
          open: number
        }[];
      };
      post_movement: {
        Args: {
          p_lot_id: string
          p_type: Database["public"]["Enums"]["movement_type"]
          p_qty_signed: number
          p_unit: Database["public"]["Enums"]["unit_code"]
          p_reference_type?: string
          p_reference_id?: string
          p_user?: string
        };
        Returns: string;
      };
      product_available_cost: {
        Args: {
          p_product_id: string
        };
        Returns: number;
      };
      product_available_quantity: {
        Args: {
          p_product_id: string
          p_warehouse_id: string
          p_unit: Database["public"]["Enums"]["unit_code"]
        };
        Returns: number;
      };
      production_order_cost: {
        Args: {
          p_po_id: string
        };
        Returns: {
          raw_material_id: string
          sku: string
          name: string
          consumed_quantity: number
          unit: Database["public"]["Enums"]["unit_code"]
          line_cost: number
        }[];
      };
      public_metrics: {
        Args: Record<PropertyKey, never>;
        Returns: Json;
      };
      purchase_order_exceptions: {
        Args: {
          p_supplier_id?: string
        };
        Returns: {
          purchase_order_id: string
          code: string
          supplier_id: string
          supplier_name: string
          ordered_value: number
          received_value: number
          billed_net: number
          variance: number
          match_status: string
        }[];
      };
      purchase_order_register: {
        Args: {
          p_po_id?: string
        };
        Returns: {
          purchase_order_id: string
          code: string
          supplier_id: string
          supplier_name: string
          warehouse_name: string
          order_date: string
          status: string
          line_count: number
          ordered_value: number
          received_value: number
          billed: number
          billed_tax: number
          billed_net: number
          variance: number
          match_status: string
        }[];
      };
      receivables_aging: {
        Args: {
          p_as_of?: string
        };
        Returns: {
          customer_id: string
          customer_name: string
          issued_document_id: string
          document_number: string
          issued_at: string
          due_date: string
          days_overdue: number
          bucket: string
          total: number
          paid: number
          open: number
        }[];
      };
      receive_purchase_order: {
        Args: {
          p_po_id: string
          p_receipts: Json
        };
        Returns: undefined;
      };
      record_bill_payment: {
        Args: {
          p_bill_id: string
          p_amount: number
          p_paid_date?: string
          p_method?: string
          p_reference?: string
        };
        Returns: string;
      };
      record_document_email: {
        Args: {
          p_issued_document_id: string
          p_recipient: string
          p_subject: string
          p_message: string
        };
        Returns: string;
      };
      record_invoice_payment: {
        Args: {
          p_issued_document_id: string
          p_amount: number
          p_paid_date?: string
          p_method?: string
          p_reference?: string
        };
        Returns: string;
      };
      record_qc: {
        Args: {
          p_lot_id: string
          p_status: Database["public"]["Enums"]["qc_status"]
          p_sg?: number
          p_alcohol?: number
          p_notes?: string
          p_user?: string
        };
        Returns: undefined;
      };
      record_statement_email: {
        Args: {
          p_customer_id: string
          p_period_start: string
          p_period_end: string
          p_recipient: string
          p_subject: string
        };
        Returns: string;
      };
      sales_order_lines_costed: {
        Args: {
          p_order_id: string
        };
        Returns: {
          line_id: string
          product_id: string
          sku: string
          name: string
          quantity: number
          unit: Database["public"]["Enums"]["unit_code"]
          unit_price: number
          est_unit_cost: number
          line_revenue: number
          expected_margin: number
          shipped_quantity: number
          cogs: number
          realized_margin: number
          available_quantity: number
          returned_quantity: number
        }[];
      };
      ship_sales_order: {
        Args: {
          p_order_id: string
          p_user?: string
        };
        Returns: undefined;
      };
      ship_sales_order_lines: {
        Args: {
          p_order_id: string
          p_lines: Json
          p_user?: string
        };
        Returns: undefined;
      };
      supplier_ledger: {
        Args: {
          p_supplier_id: string
          p_start: string
          p_end: string
        };
        Returns: {
          entry_date: string
          entry_type: string
          reference: string
          debit: number
          credit: number
          balance: number
        }[];
      };
      tax_report: {
        Args: {
          p_start: string
          p_end: string
        };
        Returns: {
          period_start: string
          period_end: string
          output_tax: number
          taxable_sales: number
          invoice_count: number
          input_tax: number
          taxable_purchases: number
          bill_count: number
          net_payable: number
        }[];
      };
      tax_report_lines: {
        Args: {
          p_start: string
          p_end: string
        };
        Returns: {
          side: string
          document_number: string
          doc_date: string
          party_code: string
          party_name: string
          party_tax_id: string
          taxable_base: number
          tax_amount: number
        }[];
      };
      trace_lot_ancestors: {
        Args: {
          p_lot_id: string
        };
        Returns: {
          lot_id: string
          lot_code: string
          depth: number
          via_order: string
          quantity: number
          unit: Database["public"]["Enums"]["unit_code"]
        }[];
      };
      trace_lot_descendants: {
        Args: {
          p_lot_id: string
        };
        Returns: {
          lot_id: string
          lot_code: string
          depth: number
          via_order: string
          quantity: number
          unit: Database["public"]["Enums"]["unit_code"]
        }[];
      };
      void_bill: {
        Args: {
          p_id: string
          p_reason: string
        };
        Returns: undefined;
      };
      void_issued_document: {
        Args: {
          p_id: string
          p_reason: string
        };
        Returns: undefined;
      };
    };
    Enums: {
      app_role: "admin" | "production" | "qc" | "viewer";
      formula_basis: "percent" | "mass";
      halal_status: "certified" | "not_certified" | "in_review";
      lot_status: "available" | "quarantine" | "expired" | "consumed" | "rejected";
      material_category: "aroma_chemical" | "essential_oil" | "fixative" | "solvent" | "water" | "packaging";
      movement_type: "receipt" | "issue" | "production_in" | "adjustment" | "shipment" | "return";
      production_status: "planned" | "in_progress" | "completed" | "cancelled";
      qc_status: "pending" | "passed" | "failed";
      sales_order_status: "draft" | "confirmed" | "shipped" | "cancelled" | "partially_shipped";
      unit_code: "kg" | "g" | "mg" | "l" | "ml";
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

type PublicSchema = Database['public'];

export type Tables<T extends keyof PublicSchema['Tables']> = PublicSchema['Tables'][T]['Row'];
export type TablesInsert<T extends keyof PublicSchema['Tables']> = PublicSchema['Tables'][T]['Insert'];
export type TablesUpdate<T extends keyof PublicSchema['Tables']> = PublicSchema['Tables'][T]['Update'];
export type Enums<T extends keyof PublicSchema['Enums']> = PublicSchema['Enums'][T];
